import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ENV ft Tanstack",
  description: "Generated by create next app",
  openGraph:{
    title: "Testing ENV With Tanstack",
    description: "Ot jg dak te, lazy to sse",
    siteName: "ENV ft Tanstack",
    images: "https://em-content.zobj.net/social/emoji/middle-finger.png",
    locale: "en_US",
    type: "website",

  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
